### PR TITLE
uart: set baudrate as configured in config file

### PR DESCRIPTION
**Pull request by grischi**
This PR extends the method for connecting to a serially connected sbg Ellipse D with unknown baudrate. If the baudrate from the .yaml config file does not work, one after the other possible baudrate is tried. Once a baudrate is found where connecting succeeds, it is used to set the baudrate from the .yaml config file on the device and re-connect.

### CODE REVIEW

**Comment by tolesam** [comment]
@grischi 
Thanks you for your feedback.

When running your solution with an Ellipse D it doesn't work as expected.
The baudrate is found but we don't receive any data from the Ellipse.
By removing the call of setDeviceBaudrate() it works.

However, having a fixed list of baudrate in the code avoids being able to update it easily.
A preferred solution would be to support a baudrate list directly in the yaml configuration file so each user can define the baudrates he wants to test.
For example you could have the following configuration and then test for only 921600 and 115200 baudrates that would match with the desired and the default baudrates.
```
[...]
baudRate:
    - 921600
    - 115200
[...]
```
Moreover that would allow to extend with new possible values without having to build a new firmware.

**Comment by grischi** [comment]
Hi @tolesam ,

I was able to reproduce the problem on our side and pushed a fix, so setting the baudrate shall now work.

**Comment by tolesam** [comment]
@grischi 
Thank you, however fallback baudrates are still hardcoded and then avoid to make it evolved using the configuration only.
Could you change to support the following in the configuration file and then remove hardcoded baurates list:
```yaml
      # Baud rate (4800 ,9600 ,19200 ,38400 ,115200 [default],230400 ,460800 ,921600)
      baudRate: 115200

      # Fallback baud rates to test if baudRate doesn't work
      fallbackBaudRates:
        - 115200
        - 921600
```

**Comment by grischi** [comment]
replaced with https://github.com/SBG-Systems/sbg_ros2_driver/pull/41

**Pull request closed without merging**
